import React from 'react'

import reducer from './TemplatesReducers'


const Context = React.createContext();

export class Provider extends React.Component {
    state = {
        selectedElement: 'headerBtnLeft',
		editMode: 'on',
        previewSize:'HelthCareTemplatePC',
        preview: 'on',
        dispatch: action => this.setState(state => reducer(state, action)),

		//test
		header: {
			backgroundImge: {
				backgroundImage: "url()",
				backgroundRepeat: '',
				backgroundPosition: '',
				backgroundSize: '',
				backgroundOrigin: '',
				// for parallax
				backgroundAttachment: '',
				// fallback color

				//balend mode Lvl3
				// backgroundBlendMode: '',

			},
			backgroundVIdeo: {

			},
			backgroundSolidCOlor: {
				backgroundColor: '',
			},
			title: {
				id: 'headerTitle',
				//actionType: 'EDIT_HEADER_TITILE',
				content: "Main titile2",
				fontSize: '',
				fontType: "",
				fontWeight: "",
				color: "",
				textTransform: "",
				fontStyle: "",
				textAlign: "",
				textDecoration: "",
				lineHeight: "",

				//new
				letterSpacing: '',
				marginTop: '',
				marginLeft: '',
				marginBottom: '',
				marginRight: '',
				paddingTop: '',
				paddingLeft: '',
				paddingBottom: '',
				paddingRight: '',
				//new advanced

			},
			description: {
				id: "headerDescription",

				content: "Description of THe page Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum repellat autem voluptates et, enim numquam.Ipsum repellat autem voluptates et, enim numquam.",
				fontSize: '' + 'px',
				fontType: "",
				fontWeight: "",
				fontColor: "",
				textTransform: "",
				fontStyle: "",
				textAlign: "",
				textDecoration: "",
				lineHeight: "",
				letterSpacing: '',


			},

			buttonLeft: {
				id: 'headerBtnLeft',
				actionType: 'EDIT_HEADER_BUTTON_LEFT',
				background: '',
				border: '',
				borderThickness: '',
				borderType: '',
				borderColor: '',
				borderRadius: '',

				content: "Button Left",
				fontSize: '',
				fontType: "",
				fontWeight: "",
				color: "",
				textTransform: "",
				fontStyle: "",
				textAlign: "",
				textDecoration: "",
				letterSpacing: '',

				boxShadowColor: 'red',
				boxShadowBlur: '10px',
				boxShadowSpread: '10px',
				boxShadowHorizontal: '10px',
				boxShadowVertical: '10px',

				hoverBackground: '',
				hoverBorder: '',
				hoverBorderThiknes: '',
				hoverBorderType: '',
				hoverBorderColor: '',
				hoverBorderRadius: '',

				hoverContent: "",
				hoverFontSize: '',
				hoverFontType: "",
				hoverFontWeight: "",
				color: "",
				hoverTextTransform: "",
				hoverFontStyle: "",
				hoverTextAlign: "",
				hoverTextDecoration: "",

				hoverBoxShadowColor: '',
				hoverBoxShadowBlurRadius: '',
				hoverBoxShadowSpreadRadius: '',
				hoverBoxShadowHorizontal: '',
				hoverBoxShadowVertical: '',

			},
			buttonRight: {
				id: 'headerBtnRight',
				actionType: 'EDIT_HEADER_BUTTON_RIGHT',
				background: '',
				border: '',
				borderThiknes: '',
				borderType: '',
				borderColor: '',
				borderRadius: '',

				content: "Button right",
				fontSize: '',
				fontType: "",
				fontWeight: "",
				color: "",
				textTransform: "",
				fontStyle: "",
				textAlign: "",
				textDecoration: "",

				boxShadowColor: 'red',
				boxShadowBlur: '10px',
				boxShadowSpread: '10px',
				boxShadowHorizontal: '10px',
				boxShadowVertical: '10px',

				hoverBackground: '',
				hoverBorder: '',
				hoverBorderThiknes: '',
				hoverBorderType: '',
				hoverBorderColor: '',
				hoverBorderRadius: '',

				hoverContent: "",
				hoverFontSize: '',
				hoverFontType: "",
				hoverFontWeight: "",
				color: "",
				hoverTextTransform: "",
				hoverFontStyle: "",
				hoverTextAlign: "",
				hoverTextDecoration: "",

				hoverBoxShadowColor: '',
				hoverBoxShadowBlurRadius: '',
				hoverBoxShadowSpreadRadius: '',
				hoverBoxShadowHorizontal: '',
				hoverBoxShadowVertical: '',
			},
		},
		game:{
			title: {
				id: 'gameTitle',
				//actionType: 'EDIT_HEADER_TITILE',
				content: "YOUR QUIZ",
				fontSize: '',
				fontType: "",
				fontWeight: "",
				color: "",
				textTransform: "",
				fontStyle: "",
				textAlign: "",
				textDecoration: "",
				lineHeight: "",

				//new
				letterSpacing: '',
				marginTop: '',
				marginLeft: '',
				marginBottom: '',
				marginRight: '',
				paddingTop: '',
				paddingLeft: '',
				paddingBottom: '',
				paddingRight: '',
				//new advanced

			},
			description: {
				id: "gameDescription",

				content: "Description of THe page Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum repellat autem voluptates et, enim numquam.Ipsum repellat autem voluptates et, enim numquam.",
				fontSize: '' + 'px',
				fontType: "",
				fontWeight: "",
				fontColor: "",
				textTransform: "",
				fontStyle: "",
				textAlign: "",
				textDecoration: "",
				lineHeight: "",
				letterSpacing: '',


			},

		},

		offers: {
			title: {
				id: "offersTitle",
				actionType: 'EDIT_OFFERS_TITILE',
				content: "Offers main title",
				fontSize: '50px',
				fontType: "",
				fontWeight: "500",
				color: "",
				textTransform: "",
				fontStyle: "",
				textAlign: "center",
				textDecoration: "",
				lineHeight: "",

			},
			cards:{
				id: 'offersCards',
				background: 'red',
				border: 'solid',
				borderThickness: '10px',
				borderType: '',
				borderColor: 'black',
				borderRadius: '',

				//CONTENT - sadrzi koliko ce ikona da renderuje dodavanje i oduzimanje 

				boxShadowColor: 'red',
				boxShadowBlur: '10px',
				boxShadowSpread: '10px',
				boxShadowHorizontal: '10px',
				boxShadowVertical: '10px',

				hoverBackground: '',
				hoverBorder: '',
				hoverBorderThiknes: '',
				hoverBorderType: '',
				hoverBorderColor: '',
				hoverBorderRadius: '',

				

				hoverBoxShadowColor: '',
				hoverBoxShadowBlurRadius: '',
				hoverBoxShadowSpreadRadius: '',
				hoverBoxShadowHorizontal: '',
				hoverBoxShadowVertical: '',

			},
			cardList: [
				{
					title: {
						id: ``,
						actionType: 'EDIT_OFFERS_CARD1_TITILE',
						content: "card 121 titile",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",
						lineHeight: "",

					},
					description: {
						id: "",
						content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
						fontSize: "",
						fontType: "",
						fontWeight: "",
						fontColor: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",
						lineHeight: "",
					},
					button: {
						id: '',
						//actionType: 'EDIT_HEADER_BUTTON_LEFT',
						background: '',
						border: '',
						borderThickness: '',
						borderType: '',
						borderColor: '',
						borderRadius: '',

						content: "Learn More",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",

						boxShadowColor: '',
						boxShadowBlur: '',
						boxShadowSpread: '',
						boxShadowHorizontal: '',
						boxShadowVertical: '',

						hoverBackground: '',
						hoverBorder: '',
						hoverBorderThiknes: '',
						hoverBorderType: '',
						hoverBorderColor: '',
						hoverBorderRadius: '',

						hoverContent: "",
						hoverFontSize: '',
						hoverFontType: "",
						hoverFontWeight: "",
						color: "",
						hoverTextTransform: "",
						hoverFontStyle: "",
						hoverTextAlign: "",
						hoverTextDecoration: "",

						hoverBoxShadowColor: '',
						hoverBoxShadowBlurRadius: '',
						hoverBoxShadowSpreadRadius: '',
						hoverBoxShadowHorizontal: '',
						hoverBoxShadowVertical: '',

					},
					icon: {
						id: '',
						icon: 'fas fa-leaf',
						color: '',
						fontSize: '',
						// textAlign: 'right'
					}

				},
				{
					title: {
						id: "",
						actionType: 'EDIT_OFFERS_CARD2_TITILE',
						content: "card 2 titile",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",
						lineHeight: "",

					},
					description: {
						id: "",
						content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
						fontSize: "",
						fontType: "",
						fontWeight: "",
						fontColor: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",
						lineHeight: "",
					},
					button: {
						id: '',
						//actionType: 'EDIT_HEADER_BUTTON_LEFT',
						background: '',
						border: '',
						borderThickness: '',
						borderType: '',
						borderColor: '',
						borderRadius: '',

						content: "Learn More",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",

						boxShadowColor: '',
						boxShadowBlur: '',
						boxShadowSpread: '',
						boxShadowHorizontal: '',
						boxShadowVertical: '',

						hoverBackground: '',
						hoverBorder: '',
						hoverBorderThiknes: '',
						hoverBorderType: '',
						hoverBorderColor: '',
						hoverBorderRadius: '',

						hoverContent: "",
						hoverFontSize: '',
						hoverFontType: "",
						hoverFontWeight: "",
						color: "",
						hoverTextTransform: "",
						hoverFontStyle: "",
						hoverTextAlign: "",
						hoverTextDecoration: "",

						hoverBoxShadowColor: '',
						hoverBoxShadowBlurRadius: '',
						hoverBoxShadowSpreadRadius: '',
						hoverBoxShadowHorizontal: '',
						hoverBoxShadowVertical: '',

					},
					icon: {
						id: '',
						icon: 'fas fa-user-md',
						color: '',
						fontSize: '',
						// textAlign: 'right'
					}

				},
				{
					title: {
						id: "",
						actionType: 'EDIT_OFFERS_CARD3_TITILE',
						content: "card 3 titile",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",
						lineHeight: "",

					},
					description: {
						id: "",
						content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
						fontSize: "",
						fontType: "",
						fontWeight: "",
						fontColor: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",
						lineHeight: "",
					},
					button: {
						id: '',
						//actionType: 'EDIT_HEADER_BUTTON_LEFT',
						background: '',
						border: '',
						borderThickness: '',
						borderType: '',
						borderColor: '',
						borderRadius: '',

						content: "Learn More",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",

						boxShadowColor: '',
						boxShadowBlur: '',
						boxShadowSpread: '',
						boxShadowHorizontal: '',
						boxShadowVertical: '',

						hoverBackground: '',
						hoverBorder: '',
						hoverBorderThiknes: '',
						hoverBorderType: '',
						hoverBorderColor: '',
						hoverBorderRadius: '',

						hoverContent: "",
						hoverFontSize: '',
						hoverFontType: "",
						hoverFontWeight: "",
						color: "",
						hoverTextTransform: "",
						hoverFontStyle: "",
						hoverTextAlign: "",
						hoverTextDecoration: "",

						hoverBoxShadowColor: '',
						hoverBoxShadowBlurRadius: '',
						hoverBoxShadowSpreadRadius: '',
						hoverBoxShadowHorizontal: '',
						hoverBoxShadowVertical: '',

					},
					icon: {
						id: '',
						icon: 'fas fa-briefcase-medical',
						color: '',
						fontSize: '',
						// textAlign: 'right'
					}

				},
				{
					title: {
						id: "",
						actionType: 'EDIT_OFFERS_CARD4_TITILE',
						content: "card 4 titile",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",
						lineHeight: "",

					},
					description: {
						id: "",
						content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
						fontSize: "",
						fontType: "",
						fontWeight: "",
						fontColor: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",
						lineHeight: "",
					},
					button: {
						id: '',
						//actionType: 'EDIT_HEADER_BUTTON_LEFT',
						background: '',
						border: '',
						borderThickness: '',
						borderType: '',
						borderColor: '',
						borderRadius: '',

						content: "Learn More",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",

						boxShadowColor: '',
						boxShadowBlur: '',
						boxShadowSpread: '',
						boxShadowHorizontal: '',
						boxShadowVertical: '',

						hoverBackground: '',
						hoverBorder: '',
						hoverBorderThiknes: '',
						hoverBorderType: '',
						hoverBorderColor: '',
						hoverBorderRadius: '',

						hoverContent: "",
						hoverFontSize: '',
						hoverFontType: "",
						hoverFontWeight: "",
						color: "",
						hoverTextTransform: "",
						hoverFontStyle: "",
						hoverTextAlign: "",
						hoverTextDecoration: "",

						hoverBoxShadowColor: '',
						hoverBoxShadowBlurRadius: '',
						hoverBoxShadowSpreadRadius: '',
						hoverBoxShadowHorizontal: '',
						hoverBoxShadowVertical: '',

					},
					icon: {
						id: '',
						icon: 'fas fa-notes-medical',
						color: '',
						fontSize: '',
						// textAlign: 'right'
					}

				}
			],

		},

		boxies: {
			title: {
				id: "boxiesTitle",
				content: "Boxies main title",
				fontSize: '50px',
				fontType: "",
				fontWeight: "500",
				color: "",
				textTransform: "",
				fontStyle: "",
				textAlign: "center",
				textDecoration: "",
				lineHeight: "",

			},
			description: {
				id: 'boxiesDescription',
				content: "description boxies",
				fontSize: "",
				fontType: "",
				fontWeight: "",
				fontColor: "",
				textTransform: "",
				fontStyle: "",
				textAlign: "",
				textDecoration: "",
				lineHeight: "",

			},
			boxies:{
				id: 'boxesCards',
				background: 'red',
				border: 'solid',
				borderThickness: '10px',
				borderType: '',
				borderColor: 'black',
				borderRadius: '',

				//CONTENT - sadrzi koliko ce ikona da renderuje dodavanje i oduzimanje 

				boxShadowColor: 'red',
				boxShadowBlur: '10px',
				boxShadowSpread: '10px',
				boxShadowHorizontal: '10px',
				boxShadowVertical: '10px',

				hoverBackground: '',
				hoverBorder: '',
				hoverBorderThiknes: '',
				hoverBorderType: '',
				hoverBorderColor: '',
				hoverBorderRadius: '',

				

				hoverBoxShadowColor: '',
				hoverBoxShadowBlurRadius: '',
				hoverBoxShadowSpreadRadius: '',
				hoverBoxShadowHorizontal: '',
				hoverBoxShadowVertical: '',


			},
			boxList:[
				{
					title: {
						id: "",
						content: "box 1 titile",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",
						lineHeight: "",
	
					},
					description: {
						id: "",
						content: "box 1 desription.",
						fontSize: "",
						fontType: "",
						fontWeight: "",
						fontColor: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",
						lineHeight: "",
					},
					icon: {
						id: "",
						icon: 'far fa-check-circle',
						color: '',
						fontSize: '',
						// textAlign: 'right'
					}
	
				},
				{
					title: {
						id: "",
						content: "box 2 titile",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",
						lineHeight: "",
	
					},
					description: {
						id: "",
						content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
						fontSize: "",
						fontType: "",
						fontWeight: "",
						fontColor: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",
						lineHeight: "",
					},
					icon: {
						id: "",
						icon: 'far fa-check-circle',
						color: '',
						fontSize: '',
						// textAlign: 'right'
					}
	
				},
				{
				title: {
					id: "",
					content: "box 3 titile",
					fontSize: '',
					fontType: "",
					fontWeight: "",
					color: "",
					textTransform: "",
					fontStyle: "",
					textAlign: "",
					textDecoration: "",
					lineHeight: "",

				},
				description: {
					id: "",
					content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
					fontSize: "",
					fontType: "",
					fontWeight: "",
					fontColor: "",
					textTransform: "",
					fontStyle: "",
					textAlign: "",
					textDecoration: "",
					lineHeight: "",
				},
				icon: {
					id: "",
					icon: 'far fa-check-circle',
					color: '',
					fontSize: '',
					// textAlign: 'right'
				}

				},
				{
				title: {
					id: "",
					content: "box 4 titile",
					fontSize: '',
					fontType: "",
					fontWeight: "",
					color: "",
					textTransform: "",
					fontStyle: "",
					textAlign: "",
					textDecoration: "",
					lineHeight: "",

				},
				description: {
					id: "",
					content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
					fontSize: "",
					fontType: "",
					fontWeight: "",
					fontColor: "",
					textTransform: "",
					fontStyle: "",
					textAlign: "",
					textDecoration: "",
					lineHeight: "",
				},
				icon: {
					id: "",
					icon: 'far fa-check-circle',
					color: '',
					fontSize: '',
					// textAlign: 'right'
				}

				},
				{
				title: {
					id: "",
					content: "box 5 titile",
					fontSize: '',
					fontType: "",
					fontWeight: "",
					color: "",
					textTransform: "",
					fontStyle: "",
					textAlign: "",
					textDecoration: "",
					lineHeight: "",

				},
				description: {
					id: "",
					content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
					fontSize: "",
					fontType: "",
					fontWeight: "",
					fontColor: "",
					textTransform: "",
					fontStyle: "",
					textAlign: "",
					textDecoration: "",
					lineHeight: "",
				},
				icon: {
					id: "",
					icon: 'far fa-check-circle',
					color: '',
					fontSize: '',
					// textAlign: 'right'
				}

				},
				{
				title: {
					id: "",
					content: "box 6 titile",
					fontSize: '',
					fontType: "",
					fontWeight: "",
					color: "",
					textTransform: "",
					fontStyle: "",
					textAlign: "",
					textDecoration: "",
					lineHeight: "",

				},
				description: {
					id: "",
					content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
					fontSize: "",
					fontType: "",
					fontWeight: "",
					fontColor: "",
					textTransform: "",
					fontStyle: "",
					textAlign: "",
					textDecoration: "",
					lineHeight: "",
				},
				icon: {
					id: "",
					icon: 'far fa-check-circle',
					color: '',
					fontSize: '',
					// textAlign: 'right'
				}

				},
				{
				title: {
					id: "",
					content: "box 7 titile",
					fontSize: '',
					fontType: "",
					fontWeight: "",
					color: "",
					textTransform: "",
					fontStyle: "",
					textAlign: "",
					textDecoration: "",
					lineHeight: "",

				},
				description: {
					id: "",
					content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
					fontSize: "",
					fontType: "",
					fontWeight: "",
					fontColor: "",
					textTransform: "",
					fontStyle: "",
					textAlign: "",
					textDecoration: "",
					lineHeight: "",
				},
				icon: {
					id: "",
					icon: 'far fa-check-circle',
					color: '',
					fontSize: '',
					// textAlign: 'right'
				}

				},
				{
				title: {
					id: "",
					content: "box 8 titile",
					fontSize: '',
					fontType: "",
					fontWeight: "",
					color: "",
					textTransform: "",
					fontStyle: "",
					textAlign: "",
					textDecoration: "",
					lineHeight: "",

				},
				description: {
					id: "",
					content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
					fontSize: "",
					fontType: "",
					fontWeight: "",
					fontColor: "",
					textTransform: "",
					fontStyle: "",
					textAlign: "",
					textDecoration: "",
					lineHeight: "",
				},
				icon: {
					id: "",
					icon: 'far fa-check-circle',
					color: '',
					fontSize: '',
					// textAlign: 'right'
				}

				},
			],
			
			
			button: {
				id: "boxiesBtn",
				actionType: 'EDIT_BOXIES_BUTTON',
				background: '',
				border: '',
				borderThiknes: '',
				borderType: '',
				borderColor: '',
				borderRadius: '',

				content: "Button Boxies",
				fontSize: '',
				fontType: "",
				fontWeight: "",
				color: "",
				textTransform: "",
				fontStyle: "",
				textAlign: "",
				textDecoration: "",

				boxShadowColor: 'red',
				boxShadowBlur: '10px',
				boxShadowSpread: '10px',
				boxShadowHorizontal: '10px',
				boxShadowVertical: '10px',

				hoverBackground: '',
				hoverBorder: '',
				hoverBorderThiknes: '',
				hoverBorderType: '',
				hoverBorderColor: '',
				hoverBorderRadius: '',

				hoverContent: "",
				hoverFontSize: '',
				hoverFontType: "",
				hoverFontWeight: "",
				color: "",
				hoverTextTransform: "",
				hoverFontStyle: "",
				hoverTextAlign: "",
				hoverTextDecoration: "",

				hoverBoxShadowColor: '',
				hoverBoxShadowBlurRadius: '',
				hoverBoxShadowSpreadRadius: '',
				hoverBoxShadowHorizontal: '',
				hoverBoxShadowVertical: '',
			},

		},

		contact: {
			title: {
				id: "contactTitle",
				content: "GET IN TOUCH TODAY Contact title",
				fontSize: '',
				fontType: "",
				fontWeight: "",
				color: "",
				textTransform: "",
				fontStyle: "",
				textAlign: "",
				textDecoration: "",
				lineHeight: "",
			},
			form: [
				{
					//za input 
					id:'',
					label:'',
					classNamel:'',
					type:'',
					name:'',
					placeholder:'',

				}
			],
			button: {
				id: "contactBtn",
				actionType: 'EDIT_CONTACT_BUTTON',
				background: '',
				border: '',
				borderThiknes: '',
				borderType: '',
				borderColor: '',
				borderRadius: '',

				content: "Book Appointmant C",
				fontSize: '',
				fontType: "",
				fontWeight: "",
				color: "",
				textTransform: "",
				fontStyle: "",
				textAlign: "",
				textDecoration: "",

				boxShadowColor: '',
				boxShadowBlur: '',
				boxShadowSpread: '',
				boxShadowHorizontal: '',
				boxShadowVertical: '',

				hoverBackground: '',
				hoverBorder: '',
				hoverBorderThiknes: '',
				hoverBorderType: '',
				hoverBorderColor: '',
				hoverBorderRadius: '',

				hoverContent: "",
				hoverFontSize: '',
				hoverFontType: "",
				hoverFontWeight: "",
				color: "",
				hoverTextTransform: "",
				hoverFontStyle: "",
				hoverTextAlign: "",
				hoverTextDecoration: "",

				hoverBoxShadowColor: '',
				hoverBoxShadowBlurRadius: '',
				hoverBoxShadowSpreadRadius: '',
				hoverBoxShadowHorizontal: '',
				hoverBoxShadowVertical: '',
			}

		},

		getStarted: {
			title: {
				id: 'getStartedTitle',
				content: "GET STARTED Main titile",
				fontSize: '',
				fontType: "",
				fontWeight: "",
				color: "",
				textTransform: "",
				fontStyle: "",
				textAlign: "",
				textDecoration: "",
				lineHeight: "",

			},
			description: {
				id: 'getStartedDescription',
				content: "Description of THe page Lorem ipsum dolor sit amet consectetur.",
				fontSize: "",
				fontType: "",
				fontWeight: "",
				fontColor: "",
				textTransform: "",
				fontStyle: "",
				textAlign: "",
				textDecoration: "",
				lineHeight: "",

			},
			button: {
				id: "getStartedBtn",
				actionType: 'EDIT_GET_STARTED_BUTTON',
				background: '',
				border: '',
				borderThiknes: '',
				borderType: '',
				borderColor: '',
				borderRadius: '',

				content: "Button Get Started",
				fontSize: '',
				fontType: "",
				fontWeight: "",
				color: "",
				textTransform: "",
				fontStyle: "",
				textAlign: "",
				textDecoration: "",

				boxShadowColor: 'red',
				boxShadowBlur: '10px',
				boxShadowSpread: '10px',
				boxShadowHorizontal: '10px',
				boxShadowVertical: '10px',

				hoverBackground: '',
				hoverBorder: '',
				hoverBorderThiknes: '',
				hoverBorderType: '',
				hoverBorderColor: '',
				hoverBorderRadius: '',

				hoverContent: "",
				hoverFontSize: '',
				hoverFontType: "",
				hoverFontWeight: "",
				color: "",
				hoverTextTransform: "",
				hoverFontStyle: "",
				hoverTextAlign: "",
				hoverTextDecoration: "",

				hoverBoxShadowColor: '',
				hoverBoxShadowBlurRadius: '',
				hoverBoxShadowSpreadRadius: '',
				hoverBoxShadowHorizontal: '',
				hoverBoxShadowVertical: '',

			},
		},

		footer: {
			title: {
				id: 'footerTitle',
				content: "Main footer titile",
				fontSize: '',
				fontType: "",
				fontWeight: "",
				color: "",
				textTransform: "",
				fontStyle: "",
				textAlign: "",
				textDecoration: "",
				lineHeight: "",

			},
			description: {
				id: 'footerDescription',
				content: "Description of THE FOOTER  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum repellat autem voluptates et, enim numquam.Ipsum repellat autem voluptates et, enim numquam.",
				fontSize: "",
				fontType: "",
				fontWeight: "",
				fontColor: "",
				textTransform: "",
				fontStyle: "",
				textAlign: "",
				textDecoration: "",
				lineHeight: "",

			},
			navigation1: {
				title: {
					content: "Nav1 titile",
					fontSize: '',
					fontType: "",
					fontWeight: "",
					color: "",
					textTransform: "",
					fontStyle: "",
					textAlign: "",
					textDecoration: "",
					lineHeight: "",
				},
				items: [
					{
						id: '',
						//actionType: 'EDIT_HEADER_BUTTON_LEFT',
						path: "/home ",
						background: '',
						border: '',
						borderThickness: '',
						borderType: '',
						borderColor: '',
						borderRadius: '',

						content: "Home",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",

						boxShadowColor: '',
						boxShadowBlur: '',
						boxShadowSpread: '',
						boxShadowHorizontal: '',
						boxShadowVertical: '',

						hoverBackground: '',
						hoverBorder: '',
						hoverBorderThiknes: '',
						hoverBorderType: '',
						hoverBorderColor: '',
						hoverBorderRadius: '',

						hoverContent: "",
						hoverFontSize: '',
						hoverFontType: "",
						hoverFontWeight: "",
						color: "",
						hoverTextTransform: "",
						hoverFontStyle: "",
						hoverTextAlign: "",
						hoverTextDecoration: "",

						hoverBoxShadowColor: '',
						hoverBoxShadowBlurRadius: '',
						hoverBoxShadowSpreadRadius: '',
						hoverBoxShadowHorizontal: '',
						hoverBoxShadowVertical: '',
					},
					{
						id: 'footerNav1Item2',
						//actionType: 'EDIT_HEADER_BUTTON_LEFT',
						path: "/home",
						background: '',
						border: '',
						borderThickness: '',
						borderType: '',
						borderColor: '',
						borderRadius: '',

						content: "About",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",

						boxShadowColor: '',
						boxShadowBlur: '',
						boxShadowSpread: '',
						boxShadowHorizontal: '',
						boxShadowVertical: '',

						hoverBackground: '',
						hoverBorder: '',
						hoverBorderThiknes: '',
						hoverBorderType: '',
						hoverBorderColor: '',
						hoverBorderRadius: '',

						hoverContent: "",
						hoverFontSize: '',
						hoverFontType: "",
						hoverFontWeight: "",
						color: "",
						hoverTextTransform: "",
						hoverFontStyle: "",
						hoverTextAlign: "",
						hoverTextDecoration: "",

						hoverBoxShadowColor: '',
						hoverBoxShadowBlurRadius: '',
						hoverBoxShadowSpreadRadius: '',
						hoverBoxShadowHorizontal: '',
						hoverBoxShadowVertical: '',
					},
					{
						id: 'footerNav1Item3',
						//actionType: 'EDIT_HEADER_BUTTON_LEFT',
						path: "/home ",
						background: '',
						border: '',
						borderThickness: '',
						borderType: '',
						borderColor: '',
						borderRadius: '',

						content: "Home",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",

						boxShadowColor: '',
						boxShadowBlur: '',
						boxShadowSpread: '',
						boxShadowHorizontal: '',
						boxShadowVertical: '',

						hoverBackground: '',
						hoverBorder: '',
						hoverBorderThiknes: '',
						hoverBorderType: '',
						hoverBorderColor: '',
						hoverBorderRadius: '',

						hoverContent: "",
						hoverFontSize: '',
						hoverFontType: "",
						hoverFontWeight: "",
						color: "",
						hoverTextTransform: "",
						hoverFontStyle: "",
						hoverTextAlign: "",
						hoverTextDecoration: "",

						hoverBoxShadowColor: '',
						hoverBoxShadowBlurRadius: '',
						hoverBoxShadowSpreadRadius: '',
						hoverBoxShadowHorizontal: '',
						hoverBoxShadowVertical: '',
					},
					{
						id: 'footerNav1Item4',
						//actionType: 'EDIT_HEADER_BUTTON_LEFT',
						path: "/home",
						background: '',
						border: '',
						borderThickness: '',
						borderType: '',
						borderColor: '',
						borderRadius: '',

						content: "About",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",

						boxShadowColor: '',
						boxShadowBlur: '',
						boxShadowSpread: '',
						boxShadowHorizontal: '',
						boxShadowVertical: '',

						hoverBackground: '',
						hoverBorder: '',
						hoverBorderThiknes: '',
						hoverBorderType: '',
						hoverBorderColor: '',
						hoverBorderRadius: '',

						hoverContent: "",
						hoverFontSize: '',
						hoverFontType: "",
						hoverFontWeight: "",
						color: "",
						hoverTextTransform: "",
						hoverFontStyle: "",
						hoverTextAlign: "",
						hoverTextDecoration: "",

						hoverBoxShadowColor: '',
						hoverBoxShadowBlurRadius: '',
						hoverBoxShadowSpreadRadius: '',
						hoverBoxShadowHorizontal: '',
						hoverBoxShadowVertical: '',
					},
					{
						id: 'footerNav1Item5',
						//actionType: 'EDIT_HEADER_BUTTON_LEFT',
						path: "/home",
						background: '',
						border: '',
						borderThickness: '',
						borderType: '',
						borderColor: '',
						borderRadius: '',

						content: "About",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",

						boxShadowColor: '',
						boxShadowBlur: '',
						boxShadowSpread: '',
						boxShadowHorizontal: '',
						boxShadowVertical: '',

						hoverBackground: '',
						hoverBorder: '',
						hoverBorderThiknes: '',
						hoverBorderType: '',
						hoverBorderColor: '',
						hoverBorderRadius: '',

						hoverContent: "",
						hoverFontSize: '',
						hoverFontType: "",
						hoverFontWeight: "",
						color: "",
						hoverTextTransform: "",
						hoverFontStyle: "",
						hoverTextAlign: "",
						hoverTextDecoration: "",

						hoverBoxShadowColor: '',
						hoverBoxShadowBlurRadius: '',
						hoverBoxShadowSpreadRadius: '',
						hoverBoxShadowHorizontal: '',
						hoverBoxShadowVertical: '',
					}
				],


			},
			navigation2: {
				title: {
					id: 'footerNav2Title',
					content: "Nav2 titile",
					fontSize: '',
					fontType: "",
					fontWeight: "",
					color: "",
					textTransform: "",
					fontStyle: "",
					textAlign: "",
					textDecoration: "",
					lineHeight: "",
				},
				items: [
					{
						id: 'footerNav2Item1',
						//actionType: 'EDIT_HEADER_BUTTON_LEFT',
						path: "/home ",
						background: '',
						border: '',
						borderThickness: '',
						borderType: '',
						borderColor: '',
						borderRadius: '',

						content: "Primary Care",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",

						boxShadowColor: '',
						boxShadowBlur: '',
						boxShadowSpread: '',
						boxShadowHorizontal: '',
						boxShadowVertical: '',

						hoverBackground: '',
						hoverBorder: '',
						hoverBorderThiknes: '',
						hoverBorderType: '',
						hoverBorderColor: '',
						hoverBorderRadius: '',

						hoverContent: "",
						hoverFontSize: '',
						hoverFontType: "",
						hoverFontWeight: "",
						color: "",
						hoverTextTransform: "",
						hoverFontStyle: "",
						hoverTextAlign: "",
						hoverTextDecoration: "",

						hoverBoxShadowColor: '',
						hoverBoxShadowBlurRadius: '',
						hoverBoxShadowSpreadRadius: '',
						hoverBoxShadowHorizontal: '',
						hoverBoxShadowVertical: '',
					},
					{
						id: 'footerNav2Item2',
						//actionType: 'EDIT_HEADER_BUTTON_LEFT',
						path: "/home",
						background: '',
						border: '',
						borderThickness: '',
						borderType: '',
						borderColor: '',
						borderRadius: '',

						content: "Pharmacy",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",

						boxShadowColor: '',
						boxShadowBlur: '',
						boxShadowSpread: '',
						boxShadowHorizontal: '',
						boxShadowVertical: '',

						hoverBackground: '',
						hoverBorder: '',
						hoverBorderThiknes: '',
						hoverBorderType: '',
						hoverBorderColor: '',
						hoverBorderRadius: '',

						hoverContent: "",
						hoverFontSize: '',
						hoverFontType: "",
						hoverFontWeight: "",
						color: "",
						hoverTextTransform: "",
						hoverFontStyle: "",
						hoverTextAlign: "",
						hoverTextDecoration: "",

						hoverBoxShadowColor: '',
						hoverBoxShadowBlurRadius: '',
						hoverBoxShadowSpreadRadius: '',
						hoverBoxShadowHorizontal: '',
						hoverBoxShadowVertical: '',
					},
					{
						id: 'footerNav1Item3',
						//actionType: 'EDIT_HEADER_BUTTON_LEFT',
						path: "/home ",
						background: '',
						border: '',
						borderThickness: '',
						borderType: '',
						borderColor: '',
						borderRadius: '',

						content: "Emergency",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",

						boxShadowColor: '',
						boxShadowBlur: '',
						boxShadowSpread: '',
						boxShadowHorizontal: '',
						boxShadowVertical: '',

						hoverBackground: '',
						hoverBorder: '',
						hoverBorderThiknes: '',
						hoverBorderType: '',
						hoverBorderColor: '',
						hoverBorderRadius: '',

						hoverContent: "",
						hoverFontSize: '',
						hoverFontType: "",
						hoverFontWeight: "",
						color: "",
						hoverTextTransform: "",
						hoverFontStyle: "",
						hoverTextAlign: "",
						hoverTextDecoration: "",

						hoverBoxShadowColor: '',
						hoverBoxShadowBlurRadius: '',
						hoverBoxShadowSpreadRadius: '',
						hoverBoxShadowHorizontal: '',
						hoverBoxShadowVertical: '',
					},
					{
						id: 'footerNav2Item4',
						//actionType: 'EDIT_HEADER_BUTTON_LEFT',
						path: "/home",
						background: '',
						border: '',
						borderThickness: '',
						borderType: '',
						borderColor: '',
						borderRadius: '',

						content: "Pediatrics",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",

						boxShadowColor: '',
						boxShadowBlur: '',
						boxShadowSpread: '',
						boxShadowHorizontal: '',
						boxShadowVertical: '',

						hoverBackground: '',
						hoverBorder: '',
						hoverBorderThiknes: '',
						hoverBorderType: '',
						hoverBorderColor: '',
						hoverBorderRadius: '',

						hoverContent: "",
						hoverFontSize: '',
						hoverFontType: "",
						hoverFontWeight: "",
						color: "",
						hoverTextTransform: "",
						hoverFontStyle: "",
						hoverTextAlign: "",
						hoverTextDecoration: "",

						hoverBoxShadowColor: '',
						hoverBoxShadowBlurRadius: '',
						hoverBoxShadowSpreadRadius: '',
						hoverBoxShadowHorizontal: '',
						hoverBoxShadowVertical: '',
					},
					{
						id: 'footerNav2Item5',
						//actionType: 'EDIT_HEADER_BUTTON_LEFT',
						path: "/home",
						background: '',
						border: '',
						borderThickness: '',
						borderType: '',
						borderColor: '',
						borderRadius: '',

						content: "Urgent Care",
						fontSize: '',
						fontType: "",
						fontWeight: "",
						color: "",
						textTransform: "",
						fontStyle: "",
						textAlign: "",
						textDecoration: "",

						boxShadowColor: '',
						boxShadowBlur: '',
						boxShadowSpread: '',
						boxShadowHorizontal: '',
						boxShadowVertical: '',

						hoverBackground: '',
						hoverBorder: '',
						hoverBorderThiknes: '',
						hoverBorderType: '',
						hoverBorderColor: '',
						hoverBorderRadius: '',

						hoverContent: "",
						hoverFontSize: '',
						hoverFontType: "",
						hoverFontWeight: "",
						color: "",
						hoverTextTransform: "",
						hoverFontStyle: "",
						hoverTextAlign: "",
						hoverTextDecoration: "",

						hoverBoxShadowColor: '',
						hoverBoxShadowBlurRadius: '',
						hoverBoxShadowSpreadRadius: '',
						hoverBoxShadowHorizontal: '',
						hoverBoxShadowVertical: '',
					}
				],


			},

		}
    }
    
    render() {
        return (
            <Context.Provider value={this.state}>
				{this.props.children}
			</Context.Provider>
        )
    }
}

export const Consumer = Context.Consumer;